"""Store manager: place an order before the cutoff, follow it, confirm receipt, report issues."""

from typing import Annotated, Literal
from uuid import UUID

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.dependencies import CurrentUser, DbSession, require_roles
from app.modules.common import not_found, one, rows, scalar

router = APIRouter(prefix="/store", tags=["Store manager"])
StoreUser = Annotated[CurrentUser, Depends(require_roles("store_manager"))]


class OrderLineIn(BaseModel):
    product_id: int
    qty: float = Field(gt=0)


class PlaceOrderIn(BaseModel):
    client_request_id: UUID  # generated by the browser; a retry returns the same order
    temp: Literal["ambient", "chilled"]
    lines: list[OrderLineIn] = Field(min_length=1)


class IssueIn(BaseModel):
    line_no: int
    type: Literal["short", "damaged", "wrong_item", "not_received"]
    qty: float | None = Field(default=None, gt=0)
    note: str | None = None


class ReceiptIn(BaseModel):
    issues: list[IssueIn] = []


def _outlet(user: CurrentUser) -> int:
    if user.outlet_id is None:
        raise not_found("Outlet for this account")
    return user.outlet_id


@router.get("/outlet")
async def outlet(user: StoreUser, db: DbSession):
    """The manager's outlet with its windows and brand."""
    return await one(db, """
        SELECT o.outlet_id, o.code, o.name, b.code AS brand_code, b.name AS brand_name, d.name AS district,
               dp.name AS depot, o.unload, o.van_only,
               (SELECT jsonb_agg(DISTINCT jsonb_build_object('kind', w.kind, 'opens', w.opens, 'closes', w.closes))
                  FROM outlet_window w WHERE w.outlet_id = o.outlet_id) AS windows
        FROM outlet o JOIN brand b USING (brand_id) JOIN district d USING (district_id) JOIN depot dp ON dp.depot_id = o.depot_id
        WHERE o.outlet_id = :o""", {"o": _outlet(user)})


@router.get("/products")
async def products(user: StoreUser, db: DbSession, temp: Literal["ambient", "chilled"] | None = None):
    return await rows(db, """
        SELECT p.product_id, p.sku, p.name, p.temp, p.unit, p.unit_weight_kg, p.unit_volume_m3, p.fragile, p.hanging
        FROM product p JOIN outlet o ON o.brand_id = p.brand_id
        WHERE o.outlet_id = :o AND p.active AND (CAST(:t AS text) IS NULL OR p.temp::text = :t)
        ORDER BY p.temp, p.name""", {"o": _outlet(user), "t": temp})


@router.get("/usual")
async def usual_order(user: StoreUser, db: DbSession, temp: Literal["ambient", "chilled"] = "ambient"):
    """The outlet's usual quantities per product (pre-fills the order form)."""
    return await rows(db, """
        SELECT u.product_id, u.qty FROM outlet_usual_line u
        WHERE u.outlet_id = :o AND u.temp = CAST(:t AS temp_class)""", {"o": _outlet(user), "t": temp})


@router.get("/order-slot")
async def order_slot(user: StoreUser, db: DbSession, temp: Literal["ambient", "chilled"] = "ambient"):
    """Next delivery date this outlet can still order for, its cutoff, and any order already placed."""
    return await one(db, "SELECT * FROM order_slot(:o, CAST(:t AS temp_class))", {"o": _outlet(user), "t": temp})


@router.post("/orders", status_code=201)
async def place_order(body: PlaceOrderIn, user: StoreUser, db: DbSession):
    result = await one(db, """
        SELECT * FROM place_order(:rid, :o, CAST(:t AS temp_class), CAST(:lines AS jsonb), :u, 'store')""",
        {"rid": body.client_request_id, "o": _outlet(user), "t": body.temp,
         "lines": [line.model_dump() for line in body.lines], "u": user.user_id})
    await db.commit()
    return result


class ChangeOrderIn(BaseModel):
    lines: list[OrderLineIn] = Field(min_length=1)


@router.put("/orders/{order_id}")
async def change_order(order_id: int, body: ChangeOrderIn, user: StoreUser, db: DbSession):
    """Change what is on an order until its cutoff (409 WP167 once the cutoff has passed)."""
    if await one(db, "SELECT 1 AS x FROM order_header WHERE order_id = :id AND outlet_id = :o",
                 {"id": order_id, "o": _outlet(user)}) is None:
        raise not_found("Order")
    await rows(db, "SELECT amend_order(:id, CAST(:lines AS jsonb), :u)",
               {"id": order_id, "lines": [line.model_dump() for line in body.lines], "u": user.user_id})
    await db.commit()
    return await one(db, "SELECT order_id, confirmation_no, delivery_date FROM order_header WHERE order_id = :id",
                     {"id": order_id})


@router.get("/orders")
async def my_orders(user: StoreUser, db: DbSession):
    return await rows(db, """
        SELECT so.*, (SELECT jsonb_agg(jsonb_build_object('line_no', l.line_no, 'product_id', l.product_id, 'product', p.name, 'unit', p.unit, 'qty', l.qty)
                                      ORDER BY l.line_no)
                      FROM order_line l JOIN product p USING (product_id) WHERE l.order_id = so.order_id) AS lines
        FROM store_orders so WHERE so.outlet_id = :o
        ORDER BY so.delivery_date DESC, so.order_id DESC""", {"o": _outlet(user)})


@router.get("/orders/{order_id}")
async def order_detail(order_id: int, user: StoreUser, db: DbSession):
    order = await one(db, "SELECT * FROM store_orders WHERE order_id = :id AND outlet_id = :o",
                      {"id": order_id, "o": _outlet(user)})
    if order is None:
        raise not_found("Order")
    order["lines"] = await rows(db, """
        SELECT l.line_no, l.product_id, p.name AS product, p.unit, l.qty FROM order_line l JOIN product p USING (product_id)
        WHERE l.order_id = :id ORDER BY l.line_no""", {"id": order_id})
    order["cutoff_at"] = await scalar(db, """
        SELECT r.cutoff_at FROM order_header h JOIN run r ON r.run_id = h.run_id WHERE h.order_id = :id""", {"id": order_id})
    order["changeable"] = await scalar(db, """
        SELECT h.status = 'placed' AND now() < r.cutoff_at FROM order_header h JOIN run r ON r.run_id = h.run_id
        WHERE h.order_id = :id""", {"id": order_id})
    order["delivery"] = await one(db, """
        SELECT d.delivery_id, d.outcome, d.received_by, d.device_time AS delivered_at, u.name AS driver_name,
               v.code AS vehicle_code, v.source_id AS vehicle_source_id
        FROM current_delivery d JOIN app_user u ON u.user_id = d.driver_id
        JOIN stop s ON s.stop_id = d.stop_id JOIN route r ON r.route_id = s.route_id JOIN vehicle v ON v.vehicle_id = r.vehicle_id
        WHERE d.order_id = :id""", {"id": order_id})
    order["issues"] = await rows(db, """
        SELECT i.issue_id, i.reference_no, i.line_no, i.type, i.qty, i.note, p.name AS product
        FROM receipt_issue i JOIN order_line l ON l.order_id = i.order_id AND l.line_no = i.line_no
        JOIN product p ON p.product_id = l.product_id WHERE i.order_id = :id ORDER BY i.line_no""", {"id": order_id})
    order["receipt_lines"] = await rows(db, "SELECT * FROM receipt_comparison WHERE order_id = :id ORDER BY line_no",
                                        {"id": order_id})
    order["timeline"] = await rows(db, "SELECT * FROM order_timeline WHERE order_id = :id ORDER BY history_id",
                                   {"id": order_id})
    order["proof"] = await rows(db, """
        SELECT a.attachment_id, a.kind FROM attachment a JOIN current_delivery d ON d.delivery_id = a.delivery_id
        WHERE d.order_id = :id""", {"id": order_id})
    return order


@router.post("/orders/{order_id}/receipt")
async def confirm_receipt(order_id: int, body: ReceiptIn, user: StoreUser, db: DbSession):
    """Confirm what arrived. An empty issue list means everything arrived as delivered."""
    result = await one(db, "SELECT * FROM confirm_receipt(:id, :u, CAST(:issues AS jsonb))",
                       {"id": order_id, "u": user.user_id, "issues": [i.model_dump() for i in body.issues]})
    await db.commit()
    # issue_id lets the screen attach a photo to each issue (POST /attachments with issue_id).
    result["issues"] = await rows(db, """
        SELECT issue_id, reference_no, line_no, type, qty FROM receipt_issue WHERE receipt_id = :r ORDER BY line_no""",
        {"r": result["receipt_id"]})
    return result


@router.get("/notices")
async def notices(user: StoreUser, db: DbSession):
    return await rows(db, """
        SELECT notice_id, order_id, kind, title, body, created_at, read_at FROM notice
        WHERE outlet_id = :o ORDER BY created_at DESC LIMIT 50""", {"o": _outlet(user)})


@router.post("/notices/{notice_id}/read", status_code=204)
async def mark_read(notice_id: int, user: StoreUser, db: DbSession):
    await rows(db, "UPDATE notice SET read_at = now() WHERE notice_id = :n AND outlet_id = :o AND read_at IS NULL RETURNING 1",
               {"n": notice_id, "o": _outlet(user)})
    await db.commit()
